spring:
  application:
    name: Tutorial-Api
#  active:
#    profile: dev
  datasource:
    url:  jdbc:postgresql://ep-restless-river-71959864-pooler.ap-southeast-1.postgres.vercel-storage.com:5432/verceldb
    username: default
    password: fTD5Z4WjvnKu
eureka:
  instance:
    prefer-ip-address: true
    client:
      fetch-registry: true
      service-url:
        defaultZone: https://10.223.163.24/eureka
