spring:
  application:
    name: Tutorial-Api-Config-Server-Defualt
eureka:
  instance:
    prefer-ip-address: true
    client:
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka
